---

- name: install redis
  sudo: true
  yum: name={{ item }} state=present enablerepo=epel
  with_items:
    - redis

- name: start redis
  sudo: true
  service: name=redis enabled=yes state=started

- meta: flush_handlers
